source/app.py
from flask import Flask, render_template
import extensions
import controllers
import config

# Initialize Flask app with the template folder address
app = Flask(__name__, template_folder='templates')

# Register the controllers
app.register_blueprint(controllers.album)
app.register_blueprint(controllers.albums)
app.register_blueprint(controllers.pic)
app.register_blueprint(controllers.main)

# Listen on external IPs
# For us, listen to port 3000 so you can just run 'python app.py' to start the server
if __name__ == '__main__':
    # listen on external IPs
    app.run(host=config.env['host'], port=config.env['port'], debug=True)

source/controllers/__init__.py
from album import *
from albums import *
from pic import *
from main import *

source/controllers/album.py
from flask import *
from extensions import db
from werkzeug.utils import secure_filename
import os
import hashlib

UPLOAD_FOLDER = 'static/images/'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'bmp', 'gif', 'PNG', 'JPG', 'BMP', 'GIF'])

def allowed_file(filename):
	return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

album = Blueprint('album', __name__, template_folder='templates', url_prefix='/fbpliijy/p1')

@album.route('/album/edit', methods=['GET','POST'])
def album_edit_route():
	options = {
		"edit": True,
	}
	cur = db.cursor()

	if request.method == 'GET':
		album_id = request.args.get('albumid')
		cur.execute("SELECT * FROM Photo JOIN Contain ON Contain.picid = Photo.picid WHERE Contain.albumid = %s;", (album_id,))
		results = cur.fetchall()

		options['pictures'] = results;
		for picture in options['pictures']:
			picture['route'] = 'images/' + picture['picid'] + '.' + picture['format']
		options['album_id'] = album_id

	elif request.method == 'POST':
		album_id = request.form['albumid']
		if request.form['op'] == "delete":
			pic_id = request.form['picid']
			cur.execute("SELECT * FROM Photo WHERE picid = %s;",(pic_id,))
			results = cur.fetchone()
			picformat = results['format']
			cur.execute("DELETE FROM Photo WHERE picid = %s;",(pic_id,))
			os.remove(UPLOAD_FOLDER + pic_id + '.' + picformat)
			cur.execute("UPDATE Album SET lastupdated = CURRENT_TIMESTAMP WHERE albumid = %s;",(album_id,))
			db.commit()
			return redirect(url_for('album.album_edit_route',albumid=album_id))
		elif request.form['op'] == "add":
			# check if the post request has the file part
			if 'file' not in request.files:
				flash('No file part')
				return redirect(url_for('album.album_edit_route',albumid=album_id))
			file = request.files['file']
			# if user does not select file, browser also
			# submit a empty part without filename
			if file.filename == '':
				flash('No selected file')
				return redirect(url_for('album.album_edit_route',albumid=album_id))
			if file and allowed_file(file.filename):
				#make hash
				m = hashlib.md5()
				dot = file.filename.find('.')
				flname = file.filename[0:dot-1]
				flformat = file.filename[dot+1:len(file.filename)]
				m.update(str(album_id))
				m.update(flname)
				pic_id = m.hexdigest()

				#find sequence number
				cur.execute("SELECT sequencenum FROM Contain;")
				results = cur.fetchall()
				for obj in results:
					numbers = [obj['sequencenum']]
				seqnum = max(numbers) + 1

				cur.execute("INSERT INTO Photo VALUES(%s, %s, CURRENT_TIMESTAMP);",(str(pic_id),flformat))
				cur.execute("INSERT INTO Contain VALUES(%s, %s, %s, '');",(seqnum, album_id, pic_id))

				cur.execute("UPDATE Album SET lastupdated = CURRENT_TIMESTAMP WHERE albumid = %s;",(album_id,))

				filename = secure_filename(pic_id + '.' + flformat)
				file.save(UPLOAD_FOLDER + filename)
				db.commit()
				return redirect(url_for('album.album_edit_route',albumid=album_id))

	return render_template("album.html", **options)

@album.route('/album', methods=['GET'])
def album_route():
	options = {
		"edit": False
	}
	cur = db.cursor()

	album_id = request.args.get('albumid')
	cur.execute("SELECT * FROM Photo JOIN Contain ON Contain.picid = Photo.picid WHERE Contain.albumid = %s;", (album_id,))
	results = cur.fetchall();
	options['pictures'] = results
	options['album_id'] = album_id
	for picture in options['pictures']:
			picture['route'] = 'images/' + picture['picid'] + '.' + picture['format']

	return render_template("album.html", **options)

source/controllers/albums.py
from flask import *
from extensions import db
import os

albums = Blueprint('albums', __name__, template_folder='templates', url_prefix='/fbpliijy/p1')

@albums.route('/albums/edit', methods=['GET', 'POST'])
def albums_edit_route():
	options = {
		"edit": True,
	}
	cur = db.cursor()
	
	if request.method == 'GET':
		user = request.args.get('username')
		cur.execute("SELECT * FROM Album WHERE username= %s;", (user,))
		results = cur.fetchall()
		options['albums'] = results
		options['username'] = user

	elif request.method == 'POST':
		user = request.form['username']
		if request.form['op'] == "delete":
			albumid = request.form['albumid']
			cur.execute("SELECT * FROM Photo JOIN Contain ON Contain.picid = Photo.picid WHERE Contain.albumid = %s;",(albumid,))
			results = cur.fetchall()
			cur.execute("DELETE FROM Album WHERE albumid = %s",(albumid,))
			for result in results:
				picid = result['picid']
				format = result['format']
				cur.execute("DELETE FROM Photo WHERE picid = %s",(picid,))
				os.remove('static/images/'+ picid +'.'+ format)
			db.commit()
		elif request.form['op'] == "add":
			title = request.form['title']
			cur.execute('INSERT INTO Album VALUES(DEFAULT, %s, DEFAULT, DEFAULT, %s)', (title, user))
			db.commit()
		return redirect(url_for('albums.albums_edit_route',username=user))

	return render_template("albums.html", **options)

@albums.route('/albums', methods=['GET'])
def albums_route():
	user = request.args.get('username')

	cur = db.cursor()
	cur.execute("SELECT * FROM Album WHERE username='%s'" % user)
	results = cur.fetchall()

	options = {
		"edit": False,
		"username": user,
		"albums": results,
	}
	return render_template("albums.html", **options)

source/controllers/main.py
from flask import *
from extensions import db

main = Blueprint('main', __name__, template_folder='templates', url_prefix='/fbpliijy/p1')

@main.route('/')
def main_route():
    cur = db.cursor()
    cur.execute('SELECT * FROM User')
    results = cur.fetchall()

    options = {
        "usernames": results,
    }

    return render_template("index.html", **options)

source/controllers/pic.py
from flask import *
from extensions import db

pic = Blueprint('pic', __name__, template_folder='templates', url_prefix='/fbpliijy/p1')


@pic.route('/pic', methods=['GET'])
def pic_route():
	options = {
		"edit": False
	}
	cur = db.cursor()

	pic_id = request.args.get('picid')

	cur.execute("SELECT * FROM Photo WHERE Photo.picid = %s", (pic_id,))
	results = cur.fetchone()
	cur.execute("SELECT * FROM Contain WHERE Contain.picid = %s", (pic_id,))
	albumid = cur.fetchone()['albumid']

	cur.execute("SELECT sequencenum FROM Contain WHERE Contain.picid = %s", (pic_id,))
	current_seqnum = cur.fetchone()['sequencenum']
	cur.execute("SELECT * FROM Contain WHERE Contain.sequencenum = (SELECT min(Contain.sequencenum) FROM Contain WHERE Contain.albumid = "+str(int(albumid))+" AND Contain.sequencenum > "+str(int(current_seqnum))+" )")
	next_pic = cur.fetchone()
	cur.execute("SELECT * FROM Contain WHERE Contain.sequencenum = (SELECT max(Contain.sequencenum) FROM Contain WHERE Contain.albumid = "+str(int(albumid))+" AND Contain.sequencenum < "+str(int(current_seqnum))+" )")
	prev_pic = cur.fetchone()

	print(albumid)

	if (prev_pic is None or prev_pic['albumid'] != albumid):
		options['prev_id'] = results
	else:
		options['prev_id'] = prev_pic

	if (next_pic is None or next_pic['albumid'] != albumid):
		options['next_id'] = results
	else:
		options['next_id'] = next_pic

	options['pictures'] = results
	options['pictures']['route'] = 'images/' + pic_id + '.' + results['format']
	options['album_id'] = albumid
	
	
	return render_template("pic.html", **options)

source/templates/album.html
{% extends "base.html" %}
{% block content %}
    <h1>ALBUM</h1>
    <p class="important">
    </p>
    {% if edit %}
    
    <div class="list">
        List of pictures in this album:
    </div> 
        <br>
    
        {% for picture in pictures %}
            <form action="{{url_for('album.album_edit_route')}}" method="POST">
                <input type="hidden" name="albumid" value="{{album_id}}">
                <input type="hidden" name="picid" value="{{picture.picid}}">

                <a id="pic_{{picture.picid}}_link" href="{{url_for('pic.pic_route',picid=picture.picid)}}"><img src="{{url_for('static', filename = picture.route)}}" class="img-rounded" alt="photo" width="250" height="250"></a>
                <p><input type="submit" id="delete_pic_{{picture.picid}}" name="op" value="delete"></p>

            </form>
    
        {% endfor %}
        <form action="{{url_for('album.album_edit_route')}}" enctype='multipart/form-data' method="POST">
            <input type="hidden" name="albumid" value="{{album_id}}">
            <input type="file" name="file" id="file_input">
            <input type="submit" id="file_submit" name="op" value="add">
        </form>
    {% else %}
        <p>
        <a href="{{url_for('album.album_edit_route',albumid=album_id)}}">Edit Album</a>
        </p>
         <div class="list">
            List of pictures in this album:
         </div> 
        <br>
        {% for picture in pictures %}
            <a id="pic_{{picture.picid}}_link" href="{{url_for('pic.pic_route',picid=picture.picid)}}"><img src="{{url_for('static', filename = picture.route)}}" class="img-rounded" alt="photo" width="250" height="250"></a>
    
        {% endfor %}    
    {% endif %}
{% endblock %}

source/templates/albums.html
{% extends "base.html" %}
{% block content %}
    <h1>ALBUMS</h1>
    <p class="important">
    </p>
    {% if edit %}
        <p> Edit your albums: </p>
        <table>
            {% for album in albums %}
            <form action="{{url_for('albums.albums_edit_route')}}" method="POST">
                <tr>
                    <td><a href="{{url_for('album.album_route',albumid=album.albumid)}}">{{album.title}}</a></td>
                    <td><a href="{{url_for('album.album_edit_route',albumid=album.albumid)}}">edit</a></td>
                    <td><input type="submit" id="delete_album_{{album.albumid}}" name="op" value="delete"></td>
                    <input type="hidden" name="albumid" value="{{album.albumid}}">
                    <input type="hidden" name="username" value="{{username}}">
                </tr>
            </form>
            {% endfor %}

            <form action="{{url_for('albums.albums_edit_route')}}" method="POST">
                <input type="hidden" name="username" value="{{username}}">
                <tr>
                    <td>New: <input type="text" id="album_add_name" name="title"></td>
                    <td><input type="submit" id="album_add_submit" name="op" value="add"></td>
                    <td></td>
                </tr>
            </form>
        </table>
    {% else %}

        <a id="user_albums_edit_{{username}}" href="{{url_for('albums.albums_edit_route',username=username)}}">Edit Albums</a>
    
        {% for album in albums %}
        <p>
        <a id="album_{{album.albumid}}_link" href="{{url_for('album.album_route',albumid=album.albumid)}}">{{album.title}}</a>
        </p>
        {% endfor %}
    {% endif %}

{% endblock %}

source/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/style.css" />
    <div class="title_bar">
        <title>EECS485 - Group 61 Project 1</title>
        <h1>Spacebook</h1>
    </div>
    <meta charset="UTF-8">
    <meta name="description" content="EECS 485 Project 1">
</head>
<body>
    <header class="center">
        <h1>EECS 485 Project 1 - Group 61</h1>

        <a href="{{url_for('main.main_route')}}">Home Page</a>
        <br>
    </header>
    
    <div class="center">
    {% block content %}{% endblock %}
    </div>

    <footer class="center">
    <br>
    Copyright, don't steal our stuff, please ;).
    </footer>

    <script type="text/javascript" src="/static/js/main.js"></script>
</body>

</html>

source/templates/index.html
{% extends "base.html" %}
{% block content %}
    <p class="center">
      Welcome to the Photo album page! This website contains photos/albums from these users:
    </p>

    {% for username in usernames %}
    <p class="center">
        <a id="user_albums_{{username.username}}" href="{{url_for('albums.albums_route',username=username.username)}}">{{username.username}}</a>
    </p>
    {% endfor %}


{% endblock %}

source/templates/pic.html
{% extends "base.html" %}
{% block content %}
    <h1>PIC</h1>
    <p class="important">
      <br>
      
      <img src="{{url_for('static', filename = pictures.route)}}">
      
      <br>

      <a href="{{url_for('pic.pic_route',picid=prev_id.picid)}}"  id="prev_pic" type="submit" value="Submit">Previous</a>

      <a href="{{url_for('pic.pic_route',picid=next_id.picid)}}" id="next_pic" type="submit" value="Submit">Next</a>
      
      <br>
      <a href="{{url_for('album.album_route',albumid=album_id)}}" id="parent_album">Back to Parent Album</a>
    </p>
{% endblock %}